#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

source "/etc/openshift/node.conf"
source ${CARTRIDGE_BASE_PATH}/abstract/info/lib/util

git_repo_owner="openshift"
git_repo_folder="capedwarf-example-modules"

git_repo="${git_repo_owner}/${git_repo_folder}"

runtime_dir=${OPENSHIFT_HOMEDIR}app-root/runtime/
cd_home=${runtime_dir}capedwarf/
cd_modules=${cd_home}capedwarf-modules/jboss-as7-modules/
cd_update_script=${cd_home}update.sh
cd_transformer=${cd_home}capedwarf-modules/transformer/
cd_transformer_script=${cd_transformer}transform.sh

local_version_file=${cd_home}local_version.ini

if [ ! -d "${cd_home}" ]; then
	mkdir ${cd_home}
	echo "capedwarf_local_version=0" > ${local_version_file}
fi

source ${runtime_dir}repo/.openshift/action_hooks/utils.sh

#set capedwarf_local_version
source /dev/stdin <<< "$(cat ${local_version_file})"


load_tags
num_of_tags=${#git_tags[@]}

git_tag=${git_tags[${num_of_tags} - 1]}
set_upstream_version

is_up_to_date
if [ ${is_up_to_date_r} == "false" ]; then
	echo "Installing new CapeDwarf modules ..."
	
	for (( i=0; $i < $num_of_tags; i=$i+1 )); do
		#skip first, it is already set
		if [ $i > 0 ]; then
			git_tag=${git_tags[${num_of_tags} - 1 - $i]}
			set_upstream_version
		fi 
		
		check_requirements
		if [ ${check_requirements_r} == "true" ]; then
			update_capedwarf
			echo "capedwarf_local_version="${capedwarf_upstream_version} > ${local_version_file}
			echo "CapeDwarf installed."
			break
		fi
	done
fi

#set Admin password if it is not set yet
welcome_page_index=${runtime_dir}/repo/src/main/webapp/index.html 

if grep -q -e "^admin" ${OPENSHIFT_HOMEDIR}jbossas-7/jbossas-7/standalone/configuration/application-users.properties; then
	echo "Admin password already set."

	if [ -f $welcome_page_index ]; then
		sed -i -e s/"\"<!--replace-with-pass-->\""/"which was shown here on a first deploy"/g ${welcome_page_index}
	fi

else
	echo "Setting admin password."
	
	password=$(random_pass_required_chars)
	password=${password}$(generate_password)
	
	JBOSS_HOME_OLD=${JBOSS_HOME}
	export JBOSS_HOME=${OPENSHIFT_HOMEDIR}jbossas-7/jbossas-7/

	${JAVA_HOME}/jre/bin/java \
		-jar ${JBOSS_HOME}jboss-modules.jar \
		-mp ${cd_modules} \
		org.jboss.as.domain-add-user \
		-a -s -u admin -p ${password} -ro admin

	export JBOSS_HOME=${JBOSS_HOME_OLD}
	
	if [ -f $welcome_page_index ]; then
		#first character must be escaped because it is a special char
		sed -i -e s/"<!--replace-with-pass-->"/"\\"${password}/g ${welcome_page_index}
	fi
	
fi
