#!/bin/bash

# The pre_start_cartridge and pre_stop_cartridge hooks are *SOURCED*
# immediately before (re)starting or stopping the specified cartridge.
# They are able to make any desired environment variable changes as
# well as other adjustments to the application environment.

# The post_start_cartridge and post_stop_cartridge hooks are executed
# immediately after (re)starting or stopping the specified cartridge.

# Exercise caution when adding commands to these hooks.  They can
# prevent your application from stopping cleanly or starting at all.
# Application start and stop is subject to different timeouts
# throughout the system.

git_repo_owner="openshift"
git_repo_folder="capedwarf-example-modules"

git_repo="${git_repo_owner}/${git_repo_folder}"

runtime_dir=${OPENSHIFT_HOMEDIR}app-root/runtime/
cd_home=${runtime_dir}capedwarf/
cd_modules=${cd_home}capedwarf-modules/jboss-as7-modules/
cd_update_script=${cd_home}update.sh
cd_transformer=${cd_home}capedwarf-modules/transformer/
cd_transformer_script=${cd_transformer}transform.sh

local_version_file=${cd_home}local_version.ini

if [ ! -d "${cd_home}" ]; then
	mkdir ${cd_home}
	echo "capedwarf_local_version=0" > ${local_version_file}
fi

debug_log=${cd_home}install.log
date > $debug_log

source $OPENSHIFT_CARTRIDGE_SDK_BASH

JBOSS_PATH=${OPENSHIFT_HOMEDIR}jbossas/
export OPENSHIFT_JBOSSAS_MODULE_PATH=${OPENSHIFT_HOMEDIR}app-root/runtime/capedwarf/capedwarf-modules/jboss-as7-modules

JBOSS_SERVER_CONFIG_USER_DIR=$OPENSHIFT_DATA_DIR
touch $JBOSS_SERVER_CONFIG_USER_DIR/application-users.properties
touch $JBOSS_SERVER_CONFIG_USER_DIR/application-roles.properties
touch $JBOSS_SERVER_CONFIG_USER_DIR/mgmt-users.properties

echo "JBOSS_PATH:${JBOSS_PATH}" >> $debug_log

source ${runtime_dir}repo/.openshift/action_hooks/utils.sh
echo "Sourced utils.sh" >> $debug_log

#set capedwarf_local_version
source /dev/stdin <<< "$(cat ${local_version_file})"

echo "Sourced local_version_file" >> $debug_log
echo "capedwarf_local_version: ${capedwarf_local_version}" >> $debug_log

load_tags
num_of_tags=${#git_tags[@]}

git_tag=${git_tags[${num_of_tags} - 1]}
set_upstream_version
echo "Git tag ${git_tag}; capedwarf_upstream_version: ${capedwarf_upstream_version}; as_required: ${as_required}" >> $debug_log

is_up_to_date
if [ ${is_up_to_date_r} == "false" ]; then
	echo "Found new CapeDwarf modules ..." | tee -a $debug_log
	
	echo "num_of_tags: ${num_of_tags}" >> $debug_log
	for (( i=0; $i < $num_of_tags; i=$i+1 )); do
		echo "Trying tag i: ${i}" >> $debug_log
		#skip first, it is already set
		if [ $i -gt 0 ]; then
			git_tag=${git_tags[${num_of_tags} - 1 - $i]}
			echo "Git tag ${git_tag}" >> $debug_log
			set_upstream_version
			echo "capedwarf_upstream_version: ${capedwarf_upstream_version}; as_required: ${as_required}" >> $debug_log
			
			is_up_to_date
			if [ ${is_up_to_date_r} == "true" ]; then
				echo "Latest compatible version already installed." | tee -a $debug_log
				break;
			fi
		fi 
		
		check_requirements
		if [ ${check_requirements_r} == "true" ]; then
			echo "Updating CapeDwarf modules ..." | tee -a $debug_log
			update_capedwarf
			echo "capedwarf_local_version="${capedwarf_upstream_version} > ${local_version_file}
			echo "CapeDwarf installed." | tee -a $debug_log
			break
		fi

	done
fi

#set Admin password if it is not set yet
welcome_page_index=${runtime_dir}/repo/src/main/webapp/index.html 

if grep -q -e "^admin" ${JBOSS_SERVER_CONFIG_USER_DIR}application-users.properties; then
	echo "Admin password already set." | tee -a $debug_log

	if [ -f $welcome_page_index ]; then
		sed -i -e s/"\"<!--replace-with-pass-->\""/"which was shown here on a first deploy"/g ${welcome_page_index}
	fi

else
	echo "Setting admin password." | tee -a $debug_log
	
	password=$(random_pass_required_chars)
	password=${password}$(generate_password)
	
	JBOSS_HOME_OLD=${JBOSS_HOME}
	export JBOSS_HOME=${JBOSS_PATH}

	${JAVA_HOME}/jre/bin/java \
		-Djboss.server.config.user.dir=$JBOSS_SERVER_CONFIG_USER_DIR \
		-jar ${JBOSS_HOME}jboss-modules.jar \
		-mp ${cd_modules} \
		org.jboss.as.domain-add-user \
		-a -s -u admin -p ${password} -ro admin

	export JBOSS_HOME=${JBOSS_HOME_OLD}
	
	if [ -f $welcome_page_index ]; then
		#first character must be escaped because it is a special char
		sed -i -e s/"<!--replace-with-pass-->"/"\\"${password}/g ${welcome_page_index}
	fi
	
fi

echo "Defining java opts..." >> $debug_log
### re defrine JAVA_OPTS the same way as JBossAS cartride does, because there is no way to just add to JAVA_OPTS
resource_limits_file=`readlink -f /etc/openshift/resource_limits.conf`
if [ "$resource_limits_file" = "/etc/openshift/resource_limits.conf" ]; 
then
	source /etc/openshift/resource_limits.conf
else
	resource_limits_file_name=`basename $resource_limits_file`
	node_profile=`echo ${resource_limits_file_name/*./}`
fi

case "$node_profile" in
    micro)
        memory_options="-client -Xmx100m -XX:MaxPermSize=100m -XX:+AggressiveOpts -Dorg.apache.tomcat.util.LOW_MEMORY=true"
    ;;
    small)
        memory_options="-client -Xmx256m -XX:MaxPermSize=128m -XX:+AggressiveOpts -Dorg.apache.tomcat.util.LOW_MEMORY=true"
    ;;
    medium)
        memory_options="-client -Xmx664m -XX:MaxPermSize=128m -XX:+AggressiveOpts -Dorg.apache.tomcat.util.LOW_MEMORY=true"
    ;;
    large)
        memory_options="-Xmx1456m -XX:MaxPermSize=148m -XX:+AggressiveOpts"
    ;;
    exlarge)
        memory_options="-Xmx2888m -XX:MaxPermSize=184m -XX:+AggressiveOpts"
    ;;
    jumbo)
        memory_options="-Xmx5888m -XX:MaxPermSize=256m -XX:+AggressiveOpts"
    ;;
esac

JAVA_OPTS="$memory_options -Dorg.jboss.resolver.warning=true -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Djboss.node.name=${OPENSHIFT_GEAR_DNS} -Djgroups.bind_addr=${OPENSHIFT_JBOSSAS_IP}"

JAVA_OPTS="${JAVA_OPTS} -Djboss.server.data.dir=${OPENSHIFT_DATA_DIR}"jboss-as7
export JAVA_OPTS="${JAVA_OPTS} -Dorg.apache.tomcat.util.net.MAX_THREADS=20 -Djboss.server.security.config.dir=${JBOSS_SERVER_CONFIG_USER_DIR}"
